name: Build and Deploy Angular App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Cache node modules
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          touch .env
          echo NG_APP_BACKEND_URL = ${{ secrets.NG_APP_BACKEND_URL }} >> .env

      - name: Build Angular app
        run: npm run build --omit=dev

      - name: Transfer to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: dist/browser/*
          strip_components: 2
          target: /var/www/html
